name: Update all Tile Indices

on:
  push:
    branches: [ main ]
  schedule:
    # run tile index creation every month
    - cron: '0 1 10 * *'

jobs:
  nw:
    uses: ./.github/workflows/tindices_nw.yml

  # commit all updated tile indices
  upload_tile_indices:
    needs: [nw]
    uses: ./.github/workflows/update_tindices.yml
    with:
      commit_message: "Update tile indices"
