name: Update all Tile Indices

on:
  push:
    branches: [ main ]
  schedule:
    # run tile index creation every month
    - cron: '0 1 10 * *'

jobs:
  be-bb:
    uses: ./.github/workflows/tindices_be_bb.yml
  # TODO HE: tindex creation takes over 6 h so that the job is canceled
  # he:
  #   uses: ./.github/workflows/tindices_he.yml
  hh:
    uses: ./.github/workflows/tindices_hh.yml
  ni:
    uses: ./.github/workflows/tindices_ni.yml
  nw:
    uses: ./.github/workflows/tindices_nw.yml
  sn:
    uses: ./.github/workflows/tindices_sn.yml

  # commit all updated tile indices
  upload_tile_indices:
    needs: [be-bb,hh,ni,nw,sn]
    uses: ./.github/workflows/update_tindices.yml
    with:
      commit_message: "Update tile indices"
