name: Update NW Tile Indices

on:
  workflow_call:
    outputs:
      artifact_name:
        description: "Name des Artefakts"
        value: ${{ jobs.build.outputs.artifact_name }}

concurrency:
  group: commit-main
  cancel-in-progress: false

jobs:

  # nDSM
  update-tindex-ndsm-nw:
    uses: ./.github/workflows/tindex_creation.yml
    with:
      type: nDSM
      state: NW
      script: openNRW_nDSM_tindex.py
      tindex_file: nrw_ndom_tindex_proj.gpkg.gz
      alpine_packages: "lynx"

  # DOP
  update-tindex-dop-nw:
    uses: ./.github/workflows/tindex_creation.yml
    with:
      type: DOP
      state: NW
      script: openNRW_DOP_tindex.py
      tindex_file: openNRW_DOP10_tileindex.gpkg.gz
      alpine_packages: "lynx parallel"
