name: Tile index creation

on:
  workflow_call:
    inputs:
      type:
        required: true
        type: string
      state:
        required: true
        type: string
      script:
        required: true
        type: string
      tindex_file:
        required: true
        type: string
      epsg_for_grass:
        required: false
        type: integer
      alpine_packages:
        required: false
        type: string
      python_libs:
        required: false
        type: string
    outputs:
      artifact_name:
        description: "Tile index"
        value: ${{ jobs.update-tindex.outputs.artifact_name }}

jobs:

  update-tindex:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.set-artifact-name.outputs.artifact_name }}
    steps:
    - uses: actions/checkout@v7
    - name: Creation of tindex
      env:
        TINDEX_TYPE: ${{ inputs.type }}
        FEDERAL_STATE: ${{ inputs.state }}
        SCRIPT: ${{ inputs.script }}
        EPSG: ${{ inputs.epsg_for_grass }}
        TINDEX: ${{ inputs.tindex_file }}
        PACKAGES: ${{ inputs.alpine_packages }}
        PY_LIBS: ${{ inputs.python_libs }}
      run: |
        if [ -n "${PACKAGES}" ]; then
          sed -i "s|# federal state specific required apk installations, to be replaced within workflow yaml by setting alpine_packages|RUN apk add ${PACKAGES}|g" docker/Dockerfile
        fi
        if [ -n "${PY_LIBS}" ]; then
          sed -i "s|# federal state specific required pip installations, to be replaced within workflow yaml by setting python_libs|RUN pip3 install ${PY_LIBS}|g" docker/Dockerfile
        fi
        if [ -n "${EPSG}" ]; then
          sed -i "s|# federal state specific python script, to be replaced within workflow yaml|RUN grass -c epsg:${EPSG} /grassdb/${FEDERAL_STATE}_${TINDEX_TYPE} --exec python3 ${TINDEX_TYPE}/${FEDERAL_STATE}/${SCRIPT}|g" docker/Dockerfile
        else
          sed -i "s|# federal state specific python script, to be replaced within workflow yaml|RUN python3 ${TINDEX_TYPE}/${FEDERAL_STATE}/${SCRIPT}|g" docker/Dockerfile
        fi
        docker build -f docker/Dockerfile -t test-tindex .
        ID=$(docker create test-tindex)
        echo $ID
        docker cp $ID:/src/tile-indices/${TINDEX_TYPE}/${FEDERAL_STATE}/${TINDEX} .
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.type }}__${{ inputs.state }}
        path: ${{ inputs.tindex_file }}
