name: Update DSM HH Tile Index

on:
  push:
    branches: [ main ]
  # schedule:
  #   # run tile index creation every month
  #   - cron:  '0 2 9 * *'

jobs:
  update-tindex-ndsm-nw:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Update HH DSM tile index
    steps:
    - uses: actions/checkout@v4
    - name: Creation of DSM tindex
      run: |
        sed -i "s+RUN python3 DOP/NW/openNRW_DOP_tindex.py+RUN grass -c epsg:25832 /grassdb/HH_DSM --exec python3 DSM/HH/HH_DSM_tindex.py+g" docker/Dockerfile
        docker build -f docker/Dockerfile -t test-tindex .
        ID=$(docker create test-tindex)
        echo $ID
        docker cp $ID:/src/tile-indices/DSM/HH/hh_dom_tindex_proj.gpkg.gz DSM/HH/
    # Commit and push all changed files.
    - name: Upload DSM tindex
      # Only run on main branch push (e.g. after pull request merge).
      run: |
        ID=$(docker create test-tindex)
        echo ${ID}
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add DSM/HH/hh_dom_tindex_proj.gpkg.gz
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
