name: Update ALKIS Liegenschaftskataster Hessen Tile Index

on:
  push:
    branches:
    - main
  schedule:
    # run tile index creation every month
    - cron:  '0 1 6 * *'

jobs:
  update-tindex-alkis-lk-he:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Update HE ALKIS-LK tile index
    steps:
    - uses: actions/checkout@v4
    - name: Creation of tindex
      run: |
        sed -i "s+RUN python3 DOP/NW/openNRW_DOP_tindex.py+RUN grass -c epsg:25832 /grassdb/HE_ALKIS --exec python3 ALKIS/Liegenschaftskataster/HE/HE_ALKIS_LK_tindex.py+g" docker/Dockerfile
        docker build -f docker/Dockerfile -t test-tindex .
        ID=$(docker create test-tindex)
        echo $ID
        docker cp $ID:/src/tile-indices/ALKIS/Liegenschaftskataster/HE/HE_ALKIS_LK_tindex.gpkg.gz ALKIS/Liegenschaftskataster/HE/
    # Commit and push all changed files.
    - name: Upload tindex
      # Only run on main branch push (e.g. after pull request merge).
      run: |
        ID=$(docker create test-tindex)
        echo ${ID}
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config pull.rebase false
        git add ALKIS/Liegenschaftskataster/HE/HE_ALKIS_LK_tindex.gpkg.gz
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git pull origin main
        git push
