name: Update DSM NI Tile Index

on:
  push:
    branches: [ main ]
  schedule:
    # run tile index creation every month
    - cron:  '0 2 11 * *'

jobs:
  update-tindex-dsm-and-dtm-ni:
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Update NI DSM and DTM tile index
    steps:
    - uses: actions/checkout@v4
    - name: Creation of DSM tindex
      run: |
        sed -i "s+RUN pip3 install requests remotezip+RUN pip3 install wget+g" docker/Dockerfile
        sed -i "s+RUN python3 DOP/NW/openNRW_DOP_tindex.py+RUN python3 DSM/NI/NI_DSM_tindex.py+g" docker/Dockerfile
        docker build -f docker/Dockerfile -t test-tindex-dsm .
        ID=$(docker create test-tindex-dsm)
        echo $ID
        docker cp $ID:/src/tile-indices/DSM/NI/NI_DSM_tindex_proj.gpkg.gz DSM/NI/
    # Commit and push all changed files.
    - name: Creation of DTM tindex
      run: |
        sed -i "s+RUN python3 DSM/NI/NI_DSM_tileindex.py+RUN python3 DTM/NI/NI_DTM_tindex.py+g" docker/Dockerfile
        docker build -f docker/Dockerfile -t test-tindex-dtm .
        ID=$(docker create test-tindex-dtm)
        echo $ID
        docker cp $ID:/src/tile-indices/DTM/NI/NI_DTM_tindex_proj.gpkg.gz DTM/NI/
    # Commit and push all changed files.
    - name: Upload DTM and DSM tindex
      # Only run on main branch push (e.g. after pull request merge).
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config pull.rebase false
        git add DTM/NI/NI_DTM_tindex_proj.gpkg.gz
        git add DSM/NI/NI_DSM_tindex_proj.gpkg.gz
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git pull origin main
        git push
