name: Update all Tile Indices

on:
  workflow_call:
    inputs:
      commit_message:
        required: true
        type: string

jobs:
  # commit all updated tile indices
  upload:
    runs-on: ubuntu-latest

    if: ${{ !cancelled() }}     # ← läuft immer, außer wenn der Workflow abgebrochen wurde
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Download DOP artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          run-id: ${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: List .gpkg.gz files
        run: apt install tree | tree artifacts

      - name: copy artifacts
        run: |
          for ART in $(ls artifacts/**/*.gpkg.gz) ; do echo $ART ; DEST_TMP=${ART/artifacts\/} ; DEST=${DEST_TMP/__//}; cp $ART $DEST ; done
          rm -r artifacts

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Commit and push with retry
        run: |
          set -e
          git fetch origin main
          git merge origin/main || exit 1

          git add **/**/*.gpkg.gz
          if git diff --cached --quiet; then
            echo "Nothing to commit"
            exit 0
          fi
          git commit -m "${{ inputs.commit_message }}"
          if git push origin HEAD:main; then
            exit 0
          fi
