name: Update all Tile Indices

on:
  workflow_call:
    inputs:
      commit_message:
        required: true
        type: string

jobs:
  nw:
    uses: ./.github/workflows/tindices_nw.yml

  # commit all updated tile indices
  commit_changes:
    runs-on: ubuntu-latest
    needs: [nw]

    if: always()
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List files
        run: ls -R artifacts

      - name: copy artifacts
        run: |
          for ART in $(ls -R artifacts) ; do cp $ART ${ART//__//} ; done

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Commit and push with retry
        run: |
          set -e
          git fetch origin main
          git rebase origin/main || exit 1

          git add **/**/*.gpkg.gz
          if git diff --cached --quiet; then
            echo "Nothing to commit"
            exit 0
          fi
          git commit -m "${{ inputs.commit_message }}"
          if git push origin HEAD:main; then
            exit 0
          fi
